###

POST http://localhost:8080/login?username=A128976080&password=A128976080 HTTP/1.1

###

POST http://localhost:8080/Test/hello HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/Test/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpbmZvIjp7ImFjY291bnQiOiJBMTI4OTc2MDgwIiwibmFtZSI6IkhhbnMgSHVhbmcifSwic3ViIjoiQTEyODk3NjA4MCIsImlhdCI6MTU4NzYwNDU2NSwiZXhwIjoxNTg3NjA0NjI1fQ.O-5-9Nk47zSuWRx6JRrDMab2S7vY6OScLkj8AgbbQQU