###

POST http://localhost:8080/demo/login?username=T274606982&password=Aa1357 HTTP/1.1

###

POST http://localhost:8080/demo/Test/hello HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/demo/Test/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOnsiYWxnb3JpdGhtIjoiSG1hY1NIQTI1NiIsImVuY29kZWQiOiJvMEpFdldXd2dWQm45MWVIQmgrbFlLU0Qyb0VEck1uL0U2QmVVNGN6cXBFPSIsImZvcm1hdCI6IlJBVyIsImRlc3Ryb3llZCI6ZmFsc2V9LCJpbmZvIjp7ImFjY291bnQiOiJBMTk2NjI2MjIwIiwibmFtZSI6bnVsbCwiYXV0aG9yaXR5IjpbIkFDVElWRSJdfSwic3ViIjoiQTE5NjYyNjIyMCIsImlhdCI6MTU4NzYzODEyNiwiZXhwIjoxNTg3NjM4MTg2fQ.E20SEU70Bq7kh4gdIm5p7-VJQIsSMtVG_Kzei73mNw8

{
  "account": "T274606982",
  "password": "Aa1357"
}

###

POST http://localhost:8080/demo/Test/admin HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOnsiYWxnb3JpdGhtIjoiSG1hY1NIQTI1NiIsImVuY29kZWQiOiJkRVp2WkhoMldHMUdaeXR3V1dwbWJYRkROVFUyWVZkd1ptOTNiR2RYVDA1dkt5dDBhM0JDZUdGVVZUMD0iLCJmb3JtYXQiOiJSQVciLCJkZXN0cm95ZWQiOmZhbHNlfSwiaW5mbyI6eyJhY2NvdW50IjoiVDI3NDYwNjk4MiIsIm5hbWUiOm51bGwsImF1dGhvcml0eSI6WyJBQ1RJVkUiXX0sInN1YiI6IlQyNzQ2MDY5ODIiLCJpYXQiOjE1ODgxNDg1MDEsImV4cCI6MTU4ODE0ODU2MX0.nvOZ65QDYulcGzspd5LMgTRWG53RfijFfkCXVMVfNjI

###
