###

POST http://localhost:8080/demo/login?username=A196626220&password=Aa1357 HTTP/1.1

###

POST http://localhost:8080/demo/Test/hello HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/demo/Test/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOnsiYWxnb3JpdGhtIjoiSG1hY1NIQTI1NiIsImVuY29kZWQiOiJvMEpFdldXd2dWQm45MWVIQmgrbFlLU0Qyb0VEck1uL0U2QmVVNGN6cXBFPSIsImZvcm1hdCI6IlJBVyIsImRlc3Ryb3llZCI6ZmFsc2V9LCJpbmZvIjp7ImFjY291bnQiOiJBMTk2NjI2MjIwIiwibmFtZSI6bnVsbCwiYXV0aG9yaXR5IjpbIkFDVElWRSJdfSwic3ViIjoiQTE5NjYyNjIyMCIsImlhdCI6MTU4NzYzODEyNiwiZXhwIjoxNTg3NjM4MTg2fQ.E20SEU70Bq7kh4gdIm5p7-VJQIsSMtVG_Kzei73mNw8

{
  "account": "T274606982",
  "password": "Aa1357"
}

###

POST http://localhost:8080/demo/Test/admin HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpbmZvIjp7ImFjY291bnQiOiJBMTk2NjI2MjIwIiwibmFtZSI6bnVsbCwiYXV0aG9yaXR5IjpbIkFDVElWRSJdfSwic3ViIjoiQTE5NjYyNjIyMCIsImlhdCI6MTU4NzYzMTkwMCwiZXhwIjoxNTg3NjMxOTYwfQ.h6Jb-1DZEa-qlPGexS7T557h-NZ--c_MhVPfm6y8-Yc

###
